import { Quicksand, Lato, Oswald, Playfair_Display } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/store/StoreProvider";
import AuthCheck from "@/components/common/AuthCheck";

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
});
const lato = Lato({
  variable: "--font-lato",
  weight: "400",
  subsets: ["latin"],
});
const oswald = Oswald({
  variable: "--font-oswald",
  weight: "400",
  subsets: ["latin"],
});
const playfair = Playfair_Display({
  variable: "--font-playfair",
  weight: "400",
  subsets: ["latin"],
});
export const metadata = {
  title: "Fashvio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${quicksand.variable} ${lato.variable} ${lato.greatVibes} ${oswald.variable} ${playfair.variable} antialiased`}
      >
        <StoreProvider>
          <AuthCheck>{children}</AuthCheck>
        </StoreProvider>
      </body>
    </html>
  );
}
