import { Geist, Geist_Mono, Quicksand, Lato } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
});

const lato = Lato({
  variable: "--font-lato",
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Nest",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${quicksand.variable} ${lato.variable} antialiased`}>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
